### ISSUE TITLE
Issues installing latest release

### ISSUE THREAD

**Issue by IRONIC3D** [JenusL/sitoa#2]
Hey Jenus

I think I botched the install and now SitoA doesn't work anymore, even previous version, can you tell me what is wrong with this?

```
# ERROR : 2229 - Traceback (most recent call last):
#   File "<Script Block 2>", line 41, in XSILoadPlugin
#     Application.LoadPlugin(XSIUtils.BuildPath(in_reg.OriginPath, 'ArnoldTools.js'))
#   File "<COMObject Application>", line 2, in LoadPlugin
# COM Error: Invalid argument.  UI Items should be specified as a 1D array of String/Value pairs. - [line 40 in C:\Users\ironi\Autodesk\Softimage_2015_R2-SP2\Addons\SItoA\Application\Plugins\ArnoldDenoiser.py]
# ERROR : Traceback (most recent call last):
#   File "<Script Block 2>", line 19, in XSILoadPlugin
#     dllPath_release = Application.Plugins("Arnold Shaders").OriginPath + "bin\\nt-x86-64\\tbb42.dll";
# AttributeError: 'NoneType' object has no attribute 'OriginPath'
#  - [line 18 in C:\Tools\Softimage\VDB2SI_WG\Application\Plugins\bin\nt-x86-64\VDB_shaderDefs_ai.pys]
Application.InstallAddon("C:\\Users\\ironi\\Downloads\\SItoA-7.1.4-windows-2015.xsiaddon", 5)
```

This is now showing up even when I try to install 7.0 release.

**Comment by JenusL** [comment]
This was not a bug and it was resolved on si-community.
